---
# tasks file for lnmp
- name: add_yum repo for nginx, php, mysql
  import_tasks: add_repo.yml
- name: nginx config
  import_tasks: nginx_install_config.yml
  when: "'nginx' in group_names"
- name: php config
  import_tasks: php_install_config.yml
  when: "'php' in group_names"